# Generated by Django 4.1.7 on 2023-02-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_movie_options_alter_movie_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='location',
            field=models.TextField(default=True, max_length=255, verbose_name='Описание'),
        ),
    ]
