# Generated by Django 4.1.7 on 2023-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_movie_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='location',
            field=models.TextField(default=True, max_length=255, verbose_name='Адрес'),
        ),
    ]
