# Generated by Django 4.1.7 on 2023-02-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_movie_is_published_alter_movie_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='sfs', max_length=255, verbose_name='URL'),
        ),
    ]
